In [ ]:
import numpy as np # se coloca un alias para que sea mas facil y por lo comun que es entre programadores
import sys # este paquete maneja gunciones de sistema

#### **creand una lista de 10 elementos**

In [ ]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### **consulta el tipo de datos**

In [ ]:
type(lista1)

list

#### **Transformando una lista a un array**
recordar que un **array** es una estructura propia de la libreria de numpy

In [ ]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### **consultando el tipo de dato numerico del arreglo**

In [ ]:
arreglo.dtype

dtype('int64')

#### **crear una lista de solo numeros unos**


In [ ]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### **creando una lista de solo numeros ceros**

In [ ]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### **consultando la cantidad de memoria ocupada por la estructura**

In [ ]:
memoria_lista = sys.getsizeof (lista1)
memoria_arreglo = arreglo.nbytes

print(f"memoria ocupada por la lista: ")
print(f"memoria ocupada por la lista: ")

memoria ocupada por la lista: 
memoria ocupada por la lista: 


####  **lista de datos compuestos(transformados en array)**

In [ ]:
lista2 = ["Samir",2 ,5.6, True]

####  **transformando la lista mixta en array**
u32 hace referencia al estandar de unicode de caracteres
(lo trata como un string)

In [ ]:
arreglo2 = np.array(lista2)
arreglo2

array(['Samir', '2', '5.6', 'True'], dtype='<U32')

#### **consultando la cantidad de memoria ocupada por estructura (paquete sys)**

In [ ]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes
print(f"memoria ocupada por la lista: {memoria_lista} bytes")
print(f"memoria ocupada por el array : {memoria_arreglo} bytes")

memoria ocupada por la lista: 136 bytes
memoria ocupada por el array : 80 bytes


#### **otros metodos de numpy**

In [ ]:
print("shape:", arreglo.shape) #dimensiones
print("dimensiones:", arreglo.ndim) # numero de ejes
print("tamaño:", arreglo.size) #total de elementos
print("tipos de datos:", arreglo.dtype) #tipo almacenado
print("bytes/elementos:", arreglo.itemsize) # tamaño en bytes de cada elemento

shape: (10,)
dimensiones: 1
tamaño: 10
tipos de datos: int64
bytes/elementos: 8


#### **obeniendo el promedio del arreglo**

In [ ]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

#### **transformando el arreglo de int a float**
el metodo astype() transforma los elementos del arreglo a un tipo determinado de dato numerico

In [ ]:
new_arreglo = arreglo.astype(np.float32)# se puede especficar el tipo de numero flotante (float16) o solamente float pero el valor predeterminado es 64
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### **aplicando el paquete random**

In [ ]:
np.random.rand() # solamente genera numeros de 0 a 1

0.6732106745297742

In [ ]:
np.random.rand(5) # genera numeros aleatorios (n cantidad)

array([0.79115997, 0.47939682, 0.4333101 , 0.71324026, 0.55666533])

In [ ]:
np.random.rand(1,10,4) # genera una matriz de numeros aleatorios cantidad filas columnas

array([[[0.81622361, 0.78751577, 0.15689849, 0.4152602 ],
        [0.69377933, 0.24500637, 0.40021252, 0.55534224],
        [0.09086217, 0.71574183, 0.77414157, 0.43246171],
        [0.45531759, 0.28323736, 0.13780255, 0.63270714],
        [0.38029175, 0.79435484, 0.62366704, 0.94936571],
        [0.66422467, 0.63128348, 0.92096492, 0.08326954],
        [0.38971977, 0.79197617, 0.83347867, 0.47281041],
        [0.27603749, 0.24245425, 0.98869012, 0.86143998],
        [0.95716858, 0.61727162, 0.62602428, 0.58629624],
        [0.99775477, 0.1018106 , 0.89956675, 0.87123305]]])

In [ ]:
np.random.randint(1,100,10) # el "int" es entero entonces genera numeros enteros es igual a los anteriores de 1 al 100 y 10 numeros aleatorios
                        #^ es la cantidad
                     #^ el maximo
                #^el minmo

array([80, 51, 16, 97, 34, 28, 10, 88, 51, 10])