In [2]:
import numpy as np # se coloca un alias para que sea mas facil y por lo comun que es entre programadores
import sys # este paquete maneja gunciones de sistema

#### **creand una lista de 10 elementos**

In [5]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### **consulta el tipo de datos**

In [6]:
type(lista1)

list

#### **Transformando una lista a un array**
recordar que un **array** es una estructura propia de la libreria de numpy

In [7]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### **consultando el tipo de dato numerico del arreglo**

In [8]:
arreglo.dtype

dtype('int64')

#### **crear una lista de solo numeros unos**


In [9]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### **creando una lista de solo numeros ceros**

In [10]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### **consultando la cantidad de memoria ocupada por la estructura**

In [12]:
memoria_lista = sys.getsizeof (lista1)
memoria_arreglo = arreglo.nbytes

print(f"memoria ocupada por la lista: {memoria_lista} ")
print(f"memoria ocupada por el arreglo: {memoria_arreglo}")

memoria ocupada por la lista: 136 
memoria ocupada por el arreglo: 80


####  **lista de datos compuestos(transformados en array)**

In [14]:
lista2 = ["Samir",2 ,5.6, True]
lista2

['Samir', 2, 5.6, True]

####  **transformando la lista mixta en array**
u32 hace referencia al estandar de unicode de caracteres
(lo trata como un string)

In [15]:
arreglo2 = np.array(lista2)
arreglo2

array(['Samir', '2', '5.6', 'True'], dtype='<U32')

#### **consultando la cantidad de memoria ocupada por estructura (paquete sys)**

In [16]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes
print(f"memoria ocupada por la lista: {memoria_lista} bytes")
print(f"memoria ocupada por el array : {memoria_arreglo} bytes")

memoria ocupada por la lista: 136 bytes
memoria ocupada por el array : 80 bytes


#### **otros metodos de numpy**

In [17]:
print("shape:", arreglo.shape) #dimensiones
print("dimensiones:", arreglo.ndim) # numero de ejes
print("tamaño:", arreglo.size) #total de elementos
print("tipos de datos:", arreglo.dtype) #tipo almacenado
print("bytes/elementos:", arreglo.itemsize) # tamaño en bytes de cada elemento

shape: (10,)
dimensiones: 1
tamaño: 10
tipos de datos: int64
bytes/elementos: 8


#### **obeniendo el promedio del arreglo**

In [18]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

#### **transformando el arreglo de int a float**
el metodo astype() transforma los elementos del arreglo a un tipo determinado de dato numerico

In [19]:
new_arreglo = arreglo.astype(np.float32)# se puede especficar el tipo de numero flotante (float16) o solamente float pero el valor predeterminado es 64
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### **aplicando el paquete random**

In [21]:
np.random.rand() # solamente genera numeros de 0 a 1

0.5197332629434531

In [24]:
np.random.rand(5) # genera numeros aleatorios (n cantidad)

array([0.90846843, 0.81685704, 0.74700896, 0.60733576, 0.98245797])

In [27]:
np.random.rand(1,10,4) # genera una matriz de numeros aleatorios cantidad filas columnas

array([[[0.6773877 , 0.46318265, 0.87452556, 0.8680676 ],
        [0.66424455, 0.73978934, 0.82568726, 0.92649006],
        [0.9416611 , 0.10527332, 0.41285358, 0.26202303],
        [0.25583358, 0.33619679, 0.02330164, 0.27077349],
        [0.8460794 , 0.14350171, 0.05488155, 0.88400792],
        [0.47522873, 0.5123364 , 0.91147242, 0.67571353],
        [0.01957183, 0.12520807, 0.08448104, 0.89818364],
        [0.49746119, 0.04208431, 0.84929681, 0.64025494],
        [0.17443449, 0.60091759, 0.17530648, 0.42283813],
        [0.53636126, 0.42494031, 0.46276837, 0.03103776]]])

In [3]:
np.random.randint(1,100,10) # el "int" es entero entonces genera numeros enteros es igual a los anteriores de 1 al 100 y 10 numeros aleatorios
                        #^ es la cantidad
                     #^ el maximo
                #^el minmo

array([59,  3, 63,  5, 47, 15, 51, 37, 41, 50], dtype=int32)